### ISSUE TITLE
nice package

### ISSUE THREAD

**Issue by joeblew99** [fragmenta/server#2]
metrics is needed in terms of instrumentation.
go-metrics is what i have used, and its also used by many others.
https://github.com/armon/go-metrics

then there are the sinks, where it can be send to. 
go-metrics cna send to datadog (hosted service) but also Promethius, which is a 100% golang based metrics cloud.

**Comment by kennygrant** [comment]
Thanks, I'll take a look.

**Comment by joeblew99** [comment]
The other if defer panic,

But its more like a crash reporter
